# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sortdialog.ui'
#
# Created: Sat Apr 18 15:24:45 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SortDialog(object):
    def setupUi(self, SortDialog):
        SortDialog.setObjectName("SortDialog")
        SortDialog.resize(317, 276)
        self.gridLayout_4 = QtGui.QGridLayout(SortDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.primaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.primaryGroupBox.setObjectName("primaryGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.primaryGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.primaryGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.primaryColumnCombo = QtGui.QComboBox(self.primaryGroupBox)
        self.primaryColumnCombo.setObjectName("primaryColumnCombo")
        self.primaryColumnCombo.addItem("")
        self.gridLayout.addWidget(self.primaryColumnCombo, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.primaryGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.primaryOrderCombo = QtGui.QComboBox(self.primaryGroupBox)
        self.primaryOrderCombo.setObjectName("primaryOrderCombo")
        self.primaryOrderCombo.addItem("")
        self.primaryOrderCombo.addItem("")
        self.gridLayout.addWidget(self.primaryOrderCombo, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.primaryGroupBox, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.okButton = QtGui.QPushButton(SortDialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(SortDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.moreButton = QtGui.QPushButton(SortDialog)
        self.moreButton.setCheckable(True)
        self.moreButton.setObjectName("moreButton")
        self.verticalLayout.addWidget(self.moreButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.secondaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.secondaryGroupBox.setObjectName("secondaryGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.secondaryGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.secondaryGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.secondaryColumnCombo = QtGui.QComboBox(self.secondaryGroupBox)
        self.secondaryColumnCombo.setObjectName("secondaryColumnCombo")
        self.secondaryColumnCombo.addItem("")
        self.gridLayout_2.addWidget(self.secondaryColumnCombo, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.secondaryGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.secondaryOrderCombo = QtGui.QComboBox(self.secondaryGroupBox)
        self.secondaryOrderCombo.setObjectName("secondaryOrderCombo")
        self.secondaryOrderCombo.addItem("")
        self.secondaryOrderCombo.addItem("")
        self.gridLayout_2.addWidget(self.secondaryOrderCombo, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.secondaryGroupBox, 2, 0, 1, 1)
        self.tertiaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.tertiaryGroupBox.setObjectName("tertiaryGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.tertiaryGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.tertiaryGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.tertiaryColumnCombo = QtGui.QComboBox(self.tertiaryGroupBox)
        self.tertiaryColumnCombo.setObjectName("tertiaryColumnCombo")
        self.tertiaryColumnCombo.addItem("")
        self.gridLayout_3.addWidget(self.tertiaryColumnCombo, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tertiaryGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.tertiaryOrderCombo = QtGui.QComboBox(self.tertiaryGroupBox)
        self.tertiaryOrderCombo.setObjectName("tertiaryOrderCombo")
        self.tertiaryOrderCombo.addItem("")
        self.tertiaryOrderCombo.addItem("")
        self.gridLayout_3.addWidget(self.tertiaryOrderCombo, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.tertiaryGroupBox, 3, 0, 1, 1)

        self.retranslateUi(SortDialog)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), SortDialog.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), SortDialog.reject)
        QtCore.QObject.connect(self.moreButton, QtCore.SIGNAL("toggled(bool)"), self.secondaryGroupBox.setVisible)
        QtCore.QObject.connect(self.moreButton, QtCore.SIGNAL("toggled(bool)"), self.tertiaryGroupBox.setVisible)
        QtCore.QMetaObject.connectSlotsByName(SortDialog)
        SortDialog.setTabOrder(self.primaryColumnCombo, self.primaryOrderCombo)
        SortDialog.setTabOrder(self.primaryOrderCombo, self.secondaryColumnCombo)
        SortDialog.setTabOrder(self.secondaryColumnCombo, self.secondaryOrderCombo)
        SortDialog.setTabOrder(self.secondaryOrderCombo, self.tertiaryColumnCombo)
        SortDialog.setTabOrder(self.tertiaryColumnCombo, self.tertiaryOrderCombo)
        SortDialog.setTabOrder(self.tertiaryOrderCombo, self.okButton)
        SortDialog.setTabOrder(self.okButton, self.cancelButton)
        SortDialog.setTabOrder(self.cancelButton, self.moreButton)

    def retranslateUi(self, SortDialog):
        SortDialog.setWindowTitle(QtGui.QApplication.translate("SortDialog", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Primary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SortDialog", "Column:", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SortDialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("SortDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("SortDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.moreButton.setText(QtGui.QApplication.translate("SortDialog", "&Advenced >>>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Secondary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SortDialog", "Column:", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SortDialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Tertiary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SortDialog", "Column:", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SortDialog", "Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))

